@startuml

title "Receive message"

actor UserA as user
participant DeChat
database PODA as poda
database PODB as podb
actor UserB as partner

partner -> podb : writeOwnPOD(message)
partner -> poda : writeInbox(notificatioin)
loop 
    DeChat -> poda : checkForNotifications()
    alt found notification
        DeChat -
    end
end

@enduml