[[section-solution-strategy]]
== Solution Strategy

Language of choice is JavaScript. It's the most adequate language to develop SOLID apps at the moment both because of the support module wise it has currently such as its synergy with web applications.

Node.js modularity, asynchronity capabilities and its underlaying package managers are interesting features we want in our application therefore DeChat is made with Node. 

However we want DeChat to be client side and communicate with the POD's wherever they are hosted, removing any unneeded middle server. For that purpose, Webpack will be used to keep all the advantages of Node, client side.

For the UI because of our time constraints JQuery will be used. A framework such as Angular or React would be more of a hindrance than an advantage considering we already have to learn a lot of new tech we aren't used to as students and for this project's needs they would be overdesigning anyways.

As for data storage, JSON is our choice because it's lightweight and it's ingrained into JavaScript.
