[[section-concepts]]
== Cross-cutting Concepts

=== Data Privacy and Ownership
Perhaps the most important concept surrounding this project and what sets it apart from a conventional chat. 

Pursuing what the SOLID spec looks for, its imperative that the user regains control of his own data and that it doesnt fall in the hands of a third party.

For that purpose each user's data will be uniquely in his own POD, a personal storage to which only he has full control over. As a result, when a user sends a message this message will only be stored in that user's POD and nowhere else. His partner will be able to read this message as long as he is granted permission to do so but as said, the data will be exclusively in its author's POD.

=== Performance
Obviously we aren't trying to get top of the industry speed in our chat, but that doesnt mean that its latency should be thrown out of the window either.

Considering that decentralizing the data means we will have to connect to several PODs instead of a unique server like in a centralized architecture it might be a challenge to retain acceptable speeds.

=== Security
It's important to preserve the privacy of the data and the security of the user during the usage of DeChat. 

For that purpose all connections will be done through HTTPS. Authentication will be done with the user's POD and special care is given to the https://github.com/solid/web-access-control-spec[Authorization] as well.

=== User Experience
At the end of the day this is a chat and its meant to allow several people to communicate through it. User interface must be friendly and accessible so all kind of user profiles can use the application without any impediment or difficulty.
